### chat
POST http://localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "conversationId": "",
  "content": "hi",
  "files": [],
  "inputs": {},
  "apiKey": "app-5e2Yu8w0tCm451HcM8OEXZEb",
  "userId": "1562"
}

###
POST http://localhost:8080/v1/chat/send
Content-Type: application/json

{
  "conversationId": "",
  "content": "hi",
  "files": [],
  "inputs": {},
  "apiKey": "app-5e2Yu8w0tCm451HcM8OEXZEb",
  "userId": "1562"
}
