### chat
POST http://localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "conversationId": "",
  "content": "hi",
  "files": [],
  "inputs": {},
  "apiKey": "app-mrr2wxB6pNEwT4hYoNYubLd8",
  "userId": "1562"
}

